name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 11"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=visionOS Simulator,name=Apple Vision Pro"

    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme MainOffender -destination "${{ matrix.destination }}" test | xcbeautify
